### ISSUE TITLE
the problem of your model on huggingface

### ISSUE THREAD

**Issue by codercxer** [tae898/erc#28]
Hello, I recently read your paper. The related work in it is great and I would like to use it for some other work. When I read your paper, it says that the speaker-aware and previous utterances information are considered, but when I read your github presentation, it says “Our deployed models are neither speaker-aware nor take previous utterances into account, meaning that it only classifies one utterance at a time without the speaker information (e.g., "I love you").”Why not upload models on huggingface that take this information into account. If I want to use a model that includes this information, do I need to retrain it using your code?

**Comment by tae898** [comment]
Hi, 

Thanks for your interest in our work.
The reason the huggingface model does not take previous utterances / speakers into account is that I don't know how the users will use this model. In our paper, we trained models with the MELD and IEMOCAP data. But I can't assume that people using the huggingface model will run inference on the same data.

Actually, I've been thinking about pushing a new model to huggingface. This is my idea:

If an original conversation is something like this:

Chandler: How are you?
Joey: I'm good! And you?
Chandler: Can't be better!

Then I can make two variants of this:

A: How are you?
B: I'm good! And you?
A: Can't be better!

And

B: How are you?
A: I'm good! And you?
B: Can't be better!

Here I make two variants so that the model can more easily learn that there are two people having a conversation.
If you want to use this model, you'll have to always "prompt" your input data to something like:

A: previous utterance 1
B: previous utterance 2
A: the target utterance you want to know the emotion of.

You can probably also switch A and B and get the same results.

This way of prompting is pretty popular now in many language models, although strictly speaking RoBERTa is not an LM but an MLM.

Would you be interested in this model?

**Comment by elisim** [comment]
Wanted to ask this question too. 

Great idea :) 
Thanks for the great work, and the detailed answer 

BTW: I would like to help in anything needed.
elisimhayev@gmail.com
